import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAuthState } from "react-firebase-hooks/auth";
import HomePage from "../component/homePage";
import {
  GoogleAuthProvider,
  getAuth,
  signInWithPopup,
  signOut,
  FacebookAuthProvider
} from "firebase/auth";
import { auth, db } from "../fireb/firebApp";


async function login() {
  await signInWithPopup(auth, new FacebookAuthProvider());
}
export default function Home() {
  const [user, loading, error] = useAuthState(auth);
  if (loading) return <div>initializeApp</div>;
  if (error) {
    return <div>{error.message}</div>;
  }
  if (user) {
    return (
      <div>
        <HomePage user={user} />
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>GamifyLife</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <button onClick={login}>Login</button>
      </main>
    </div>
  );
}
